#!/usr/bin/env python3
"""Exact Korean 73-hole star, generated independently from integer axial coordinates.
Ten-hole camps share their six boundary corner nodes; see BOARD_GEOMETRY.md.
No internet image is included in the generated assets.
"""
from collections import deque, Counter
from pathlib import Path
import argparse

DIR = ((1,0),(0,1),(-1,1),(-1,0),(0,-1),(1,-1))
def rotate(p):
    q,r=p
    return (-r,q+r)

def generate():
    points=[]
    for r in range(-6,7):
        for q in range(-6,7):
            cube=(q,r,-q-r)
            if min(cube)>=-3 or max(cube)<=3:
                points.append((q,r))
    points.sort(key=lambda p:(p[1],2*p[0]+p[1]))
    assert len(points)==73
    ids={p:i for i,p in enumerate(points)}
    # Arm 0=top; subsequent arms rotate clockwise: upper right, lower right,
    # bottom, lower left, upper left. Four rows 1+2+3+4=10.
    camps=[]
    top={(3-i,-6+k) for k in range(4) for i in range(k+1)}
    for _ in range(6):
        assert len(top)==10 and top<=set(points)
        camps.append(top)
        top={rotate(p) for p in top}
    neighbors=[];jumps=[];nav=[]
    for q,r in points:
        neighbors.append([ids.get((q+dq,r+dr),-1) for dq,dr in DIR])
        jumps.append([ids.get((q+2*dq,r+2*dr),-1) if (q+dq,r+dr) in ids else -1 for dq,dr in DIR])
        x=2*q+r
        directions=[]
        for axis,sign in ((1,-1),(1,1),(0,-1),(0,1)):
            candidates=[]
            for n,(tq,tr) in enumerate(points):
                dx,dy=2*tq+tr-x,tr-r
                along=(dy if axis else dx)*sign
                cross=dx if axis else dy
                if along<=0: continue
                # UP/DOWN always use the next row, nearest column. LEFT/RIGHT
                # stay on the row when possible. This graph is independent of zoom.
                cost=(abs(dy) if axis else (0 if dy==0 else 1),
                      abs(dx) if axis else abs(dy),along,n)
                candidates.append((cost,n))
            directions.append(min(candidates)[1] if candidates else ids[(q,r)])
        nav.append(directions)
    distances=[]
    for start in range(73):
        d=[255]*73;d[start]=0;todo=deque([start])
        while todo:
            at=todo.popleft()
            for to in neighbors[at]:
                if to>=0 and d[to]==255:d[to]=d[at]+1;todo.append(to)
        assert 255 not in d
        distances.append(d)
    for start in range(73):
        seen={start};todo=[start]
        while todo:
            for to in nav[todo.pop()]:
                if to not in seen:seen.add(to);todo.append(to)
        assert len(seen)==73, (start,len(seen))
    masks=[sum(1<<a for a,c in enumerate(camps) if p in c) for p in points]
    assert sum(m==0 for m in masks)==19
    assert sum(m.bit_count()==2 for m in masks)==6
    out=['/* Generated by tools/generate_board.py; do not edit. */','#include "diamond.h"',
         'const uint8_t dg_home[4]={255,3,5,1};',
         'const uint8_t dg_goal[4]={255,0,2,4};','const DgNode dg_nodes[DG_NODES]={']
    for i,(q,r) in enumerate(points):
        array=lambda a:'{'+','.join(map(str,a))+'}'
        out.append(f' {{{q},{r},{masks[i]},{array(neighbors[i])},{array(jumps[i])},{array(nav[i])}}},')
    out+=['};','const uint8_t dg_distance[DG_NODES][DG_NODES]={']
    out+=[' {'+','.join(map(str,d))+'},' for d in distances]
    out+=['};','']
    print(f'73 nodes; camps10 each; camp union54; uncolored center19; shared6; degree histogram{dict(sorted(Counter(sum(n>=0 for n in row) for row in neighbors).items()))}')
    return '\n'.join(out)

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'src/core/board.c'
    content=generate()
    if args.check:assert path.read_text()==content, 'generated board table differs'
    else:path.write_text(content)
